# Generated by Django 3.2 on 2021-04-25 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion

from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_receita_datacadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 16, 13, 55, 606556)),
        ),
    ]
