# Generated by Django 3.2 on 2021-04-24 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomereceita', models.CharField(max_length=40)),
                ('ingredientes', models.TextField()),
                ('modoPreparo', models.TextField()),
                ('tempoPreparo', models.IntegerField()),
                ('rendimento', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=30)),
                ('dataCadastro', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 17, 2, 35, 70485))),
            ],
        ),
    ]
