# Generated by Django 3.2 on 2021-04-24 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='nomereceita',
            new_name='nomeReceita',
        ),
        migrations.AlterField(
            model_name='receita',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 17, 32, 43, 683566)),
        ),
    ]
