# Generated by Django 3.2 on 2021-04-24 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_auto_20210424_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 24, 18, 43, 28, 543315)),
        ),
    ]
