# Generated by Django 3.2 on 2021-04-25 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_auto_20210425_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 16, 30, 10, 401772)),
        ),
    ]
