# Generated by Django 3.2 on 2021-04-25 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20210425_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='img',
            field=models.ImageField(blank=True, upload_to='thumbnails/%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 16, 50, 45, 73714)),
        ),
    ]
