# Generated by Django 3.2 on 2021-04-25 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_auto_20210425_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='dataCadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 25, 18, 21, 4, 35101)),
        ),
    ]
